version: "3.0" 
services:
  # web:
  #   build:
  #     context: ./source
  #     dockerfile: ./Alejandria.WebAPI/Dockerfile
  #     ports:
  #       - 5000:5000
  #       - 5001:5001
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=Alejandria
      - POSTGRES_USER=pepito
      - POSTGRES_PASSWORD=password